FROM mvertes/alpine-mongo
MAINTAINER Sebastian Katzer "katzer@appplant.de"

ENV BUILD_PACKAGES ruby-dev gcc make libc-dev tzdata
ENV RUBY_PACKAGES ruby git ruby-bundler ruby-io-console

RUN apk update && \
    apk add --no-cache $BUILD_PACKAGES && \
    apk add --no-cache $RUBY_PACKAGES && \
    gem update bundler --no-ri --no-rdoc

RUN cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime
RUN echo "Europe/Berlin" > /etc/timezone

ENV APP_HOME /usr/app/
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/log
WORKDIR $APP_HOME

COPY Gemfile $APP_HOME
COPY Gemfile.lock $APP_HOME
RUN bundle config path vendor/bundle
RUN bundle install --no-cache --without development

COPY . $APP_HOME

RUN apk del $BUILD_PACKAGES && \
    gem uninstall minitest test-unit power_assert && \
    gem clean && \
    rm -rf /var/cache/apk/* && \
    rm -rf /usr/share/ri && \
    rm -rf $APP_HOME/vendor/bundle/cache/*.gem && \
    rm -rf $APP_HOME/vendor/bundle/extensions/* && \
    rm -rf $APP_HOME/vendor/bundle/gems/*/test && \
    rm -rf $APP_HOME/vendor/bundle/gems/*/spec && \
    rm -rf $APP_HOME/vendor/bundle/gems/*/doc && \
    rm -rf $APP_HOME/vendor/bundle/gems/*/examples && \
    rm -rf $APP_HOME/vendor/bundle/gems/**/*.md

ENV MONGO_URI=mongodb://localhost:27017/appdax

CMD ["bundle", "exec", "rspec", "spec", "--fail-fast", "--failure-exit-code", "1", "--require", "mongo_helper"]
